[project]
name = "embedding-search-sample"
version = "0.1.0"
description = ""
authors = [
    { name = "None" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai (>=1.61.1,<2.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "mypy (>=1.15.0,<2.0.0)",
    "numpy (>=2.2.2,<3.0.0)",
    "pypdf (>=5.2.0,<6.0.0)",
    "pandas-stubs (>=2.2.3.241126,<3.0.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
package-mode = false


[tool.mypy]
python_version = "3.13"
strict = true
namespace_packages = true
exclude = "(^|/|\\\\)venv($|/|\\\\)"
